### ISSUE TITLE
ResNet baseline vs. source only

### ISSUE THREAD

**Issue by DianCh** [tim-learn/SHOT#20]
Hi, thank you for sharing the wonderful work. I have a question regarding the main paper:

In table 3, 5, 7, and 8, what's the difference between "ResNet50/101" (the first line in all tables) and "Source model only"? I'm guessing "ResNet" means using the original ResNet model (replace the last fc, no "fc+bn bottleneck" proposed in the paper) trained on source and evaluate on target without any adaptation. Is that correct?

Also in table 2, what does "Source only" in the first line (with Hoffman's method) mean?

Thank you!

**Comment by tim-learn** [comment]
> Hi, thank you for sharing the wonderful work. I have a question regarding the main paper:
> 
> In table 3, 5, 7, and 8, what's the difference between "ResNet50/101" (the first line in all tables) and "Source model only"? I'm guessing "ResNet" means using the original ResNet model (replace the last fc, no "fc+bn bottleneck" proposed in the paper) trained on source and evaluate on target without any adaptation. Is that correct?
> 
> Also in table 2, what does "Source only" in the first line (with Hoffman's method) mean?
> 
> Thank you!

Hi, both 'ResNet' and 'Source model only' denote the original model fine-tuned in the source domain and evaluated in the target domain without adaptation. For fair comparisons, we report our 'source model only' since the details of the model (training/ architecture) are not different. 

Besides, for digits, 'source only' denote the original model learned in the source domain from scratch and evaluated in the target domain without adaptation. 

Hope it addresses your concerns.
